# -*- coding: utf-8 -*-
"""compone_dx.py — arma el bloque DX completo (titulo, cabecera, filas, descartadas) en dx_bloque.md.
Las cifras salen de los archivos de los lectores y de los instrumentos; la prosa es la unica parte escrita a mano."""
import glob, io, json, os, sys
from collections import Counter

SP = os.path.dirname(os.path.abspath(__file__))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
res = json.load(io.open(os.path.join(SP, "dx_resumen.json"), encoding="utf-8"))
filas = io.open(os.path.join(SP, "dx_filas.md"), encoding="utf-8").read().rstrip("\n")
desc = io.open(os.path.join(SP, "dx_descartadas.md"), encoding="utf-8").read().rstrip("\n")
cons = json.load(io.open(os.path.join(SP, "consolidado.json"), encoding="utf-8"))

V = res["veredictos"]
n_pares = res["pares"]; n_filas = res["filas"]; n_desc = res["descartadas"]
n_contr = V.get("contradice", 0); n_parte = V.get("en-parte", 0); n_comp = V.get("compatible", 0)
n_cita = sum(1 for c in cons if c["se_citan_real"])
n_conoc = sum(1 for c in cons if c["conocido"])
n_cam = sum(1 for c in cons if any(c["cambio"].values()))

titulo = ("## Bloque DX — la cacería profunda de la v5.83: %d pares de significado reportados por siete lectores, %d filas tras una segunda "
          "lectura a ciegas (%d contradicen, %d en parte, 2 son citas mal dirigidas) y %d pares que el segundo lector dio por compatibles (01-10)"
          % (n_pares, n_filas, n_contr, n_parte, n_desc))

cab = """
**De dónde sale:** `cazador-obsoletos.py` avisaba que iban 25 versiones desde la última cacería profunda (v5.58 → v5.83; su umbral es 8) y el dueño la pidió el 01-10-2026 al relanzar la skill del BRD: *«vamos con lo Pendiente: la revisión profunda de contradicciones entre reglas que no se citan entre sí»*. **Sin cambio del BRD (v5.83): son filas para aplicar después.**

**Cómo se hizo —distinto de las cacerías DF y DJ, que fueron cinco lentes con búsqueda libre y cada elemento abierto con su vecindario—:** (1) el BRD vivo entero, **1.727 elementos de §1 a §15**, se agrupó por tema con un script (TF-IDF y k-means con semilla fija) y se repartió en cinco paquetes de volumen parecido (L1: 204 elementos y 361 KB · L2: 220 y 283 KB · L3: 368 y 317 KB · L4: 421 y 304 KB · L5: 514 y 309 KB); cada lector leyó primero las nueve notas de vocabulario (`NT-001` a `NT-009`) y las tres relaciones del dueño (`RN-380`, `RN-362`, `RN-311`) y después su paquete en lotes de unos 20.000 caracteres, con por elemento las versiones en que cambió desde la v5.58, a quién cita y quién lo cita. (2) Después de cada lote cada lector escribió una **ficha** por elemento con algo que otro podría contradecir (1.415 líneas en total) y comparó el lote contra sus fichas anteriores; al acabar, repasó todas. (3) **Cruce:** un par cuyos dos elementos cayeron en paquetes distintos nunca estuvo en la cabeza de un mismo lector, así que las 1.085 fichas se reagruparon por tema sin mirar el paquete de origen (52 grupos, todos mezclan paquetes) y dos lectores más las leyeron abriendo el elemento original de cada tensión. (4) **Segunda lectura a ciegas:** cinco verificadores recibieron de cada par solo los IDs, las citas literales y los datos del instrumento —sin el razonamiento del primer lector—, abrieron los dos elementos enteros y a lo más dos vecinos, y dieron su veredicto (`contradice`, `en parte`, `compatible`, `no decidible`) con quién resuelve el hueco según los seis montones. Lectores y verificadores fueron del mismo modelo: **su acuerdo no es evidencia independiente.**

**Cifras del resultado, con cómo se midió cada una:** (a) *Hallazgos:* 114 reportados (L1 28 · L2 19 · L3 14 · L4 18 · L5 21 · cruce 7 y 7) = **113 pares distintos** —uno, `NT-003`/`RN-301`, lo reportaron dos lectores— que involucran 179 elementos; el recuento sale de leer los siete archivos con un script y juntar por par sin importar el orden. (b) **Citas:** las 113 parejas de citas literales de los primeros lectores y las citas clave de los verificadores están dentro de su elemento (`comun.contiene` sobre el BRD vivo: 113 de 113 y 0 que no pasan); eso prueba que la cita existe, no que el choque sea real. (c) **Veredicto del segundo lector:** @A@ contradicen, @B@ contradicen en parte (chocan solo en una parte del alcance o bajo un supuesto que el texto no da por escrito), @C@ compatibles, 0 sin decidir; de los @D@ compatibles, **dos pasan a fila porque son citas mal dirigidas** (`DX-56`, `DX-95`: una regla cita a otra para algo que esa otra no dice) y los otros @E@ quedan en la tabla del final con su razón, para que la próxima cacería no los vuelva a reportar. De los 90 no compatibles el segundo lector dice que 64 cambian lo que se programa, 14 no y 12 no sabe. (d) **Se citan o no:** de los 113 pares, **@F@ SÍ se citan** (un elemento cita al otro) y @G@ no (el grafo es el del BRD vivo e incluye `DA-EST`, pero no las notas `NT`, así que los 10 pares con una nota cuentan como «no se citan»): una cacería hecha para contradicciones entre elementos que no se citan encontró sobre todo pares que sí se citan, porque ningún control compara el significado de una cita con lo que el citado dice. (e) **Pares que ya tenían fila:** @H@ de 113 nombran los dos IDs en una misma fila de este enrutador o de `docs/archivo/correcciones-aplicadas.md` (criterio laxo: no se comparó que la fila trate la misma contradicción; algunas están aplicadas y el par sigue chocando, y la fila nueva lo dice): los lectores, sin saber de esas filas, volvieron a encontrar pares ya enrutados. **No se midió el recall** —no se sabe cuántas contradicciones hay—. (f) **Tocan un elemento cambiado desde la v5.58:** @I@ de los 113 pares.

**Cobertura, declarada y medida:** **impreso no es leído con atención.** Medido por el registro de `leer.py`: 1.727 de 1.727 elementos impresos, y los 501 elementos vivos que cambiaron entre la v5.59 y la v5.83 también. Declarado por los propios lectores: **689 de los 1.727 elementos (40%) estaban en lotes que leyeron más rápido** —casi todos criterios de aceptación contra la regla que prueban y elementos de una línea; entre ellos 121 de los 501 cambiados— (L1 88 de 204 · L2 77 de 220 · L3 108 de 368 · L4 102 de 421 · L5 314 de 514), y **100 elementos de L3 se leyeron de pasada sin ficha** (casos borde, criterios simples, flujos del constructor y del proveedor; los que menos atención recibieron: `CA-278`, `CA-375`, `CA-380`, `CA-381`, `CA-383`, `CA-493`, `CA-532`, `CA-575`, `DA-OUT-019`). Las fichas cubren 1.085 de los 1.727 elementos (63%): lo no fichado solo se comparó en la cabeza del lector. Uno de los dos lectores del cruce (X2) descartó 7 tensiones solo por ficha, sin abrir el original (`CA-342`+`RN-262`, `RN-137`+`AL-041`, `RG-014`+`AL-051`, `RN-321`+`RN-322`, `RN-276`+`RN-267`, `DA-EST-001`+`RN-027`, `CA-102`+`RN-390`). Los verificadores declararon lo que no abrieron por el tope de dos vecinos: `DX-106` (`RN-183`, `RN-190`, `PR-068`: tomó como cierto lo que `RN-429` les atribuye), `DX-110` (`AL-048`, de donde `RN-428` dice derivar su orden) y `DX-107` (no comprobó el estándar de la industria sobre quién ve el registro de auditoría).

**La lista de elementos cambiados:** 571 IDs en las 25 versiones (195 nuevos y 420 modificados, con solapes), 501 vivos y el resto derogados o evidencia `INV`. **Contraste con un segundo instrumento solo en las diez últimas versiones** (v5.74 a v5.83, las que `§19` del BRD conserva): el lector de historial de `cazador-obsoletos.py` y el mío dan los mismos IDs, salvo `DA-EST-004` a `007` y `NT-009`, que ese control no reconoce (ver `DX-C1`); las versiones v5.59 a v5.73 salieron de `docs/BRD-historial.md` con un solo instrumento. Sobre las dos cacerías anteriores mi lista dio 270 para la v5.50–v5.57 (la cacería DJ contó 283) y 433 para la v5.38–v5.49 (la DF contó 216): **la diferencia no se explicó**, así que la lista se usó para marcar qué cambió y no para decir cuánto cambió el BRD.

**Costo, medido:** unos 7 millones de tokens de subagentes (suma de lo que el arnés reportó por agente: cinco lectores 3,7 millones, dos de cruce 1,5 millones, cinco verificadores 1,9 millones) y unas dos horas; el límite de 5 horas del plan pasó de 0% (tras su reinicio) a 77% y el semanal de 12% a 22%, contando también los turnos de esta sesión. Para comparar: la cascada del 01-10 gastó ~5 millones en ocho lectores y 60 puntos del límite de 5 horas.

**Lo que esta corrida NO hizo:** (1) **la relectura bidireccional de lo que tocaron las v5.80 a v5.83** (a quién citan y quién los cita, §11 (4-bis); la fila de la v5.83 declara 114 elementos) no se hizo como paso aparte: solo entró lo que los lectores vieron; (2) **el vecindario completo no se abrió para cada fila**: lectores y verificadores abrieron los vecinos por ID y a lo más dos vecinos por par (dos de los cinco verificadores se pasaron del tope alguna vez, y lo dijeron: uno en dos pares y otro en uno); (3) **ninguna fila ○ la reabrió la sesión principal**, salvo `DX-C1`, `DX-C2` y `DX-C3`, que son sobre los controles; (4) «quién resuelve» es la lectura del verificador: **84 de 90 salieron «derivado» (a)**, y el verificador del cuarto paquete marcó los 26 pares así, lo que invita a desconfiar del reparto; **quien aplique una fila (a) abre el par y confirma que solo una lectura es consistente con lo escrito**, y las 3 marcadas (d) no llegan al dueño todavía: antes se corre la pregunta cero y se busca en la industria (montón b); (5) el agrupamiento por tema lo hizo un script (TF-IDF): lo que ese agrupamiento separó en paquetes distintos solo lo juntó el cruce.

**Cómo leer estas filas:** todas nacen ○ SIN VERIFICAR (las dos citas de cada fila pasaron el script; el veredicto es lectura de un modelo). **Antes de actuar sobre una se abren los dos elementos del par con `tools/elemento.py` (trae el vecindario) y se buscan sus citas.** «Qué cede» y «quién resuelve» son lecturas, no decisiones del dueño. **Las citas entre « » son literales y `citas-verificadas.py` las comprueba; las citas entre ‹ › son literales de elementos `AC-`, `NT-` o `AC-ECO-`, familias que ese control no sabe abrir (`DX-C3`), y las comprobó el script que generó las filas; las frases del segundo lector que no son citas literales van sin comillas de cita.** La numeración `DX-n` es la del par (1 a 113) y no cambia: los pares compatibles conservan su número en la tabla del final. `DX-C1`, `DX-C2` y `DX-C3` son sobre los controles, no sobre el BRD.
"""
for tok, val in zip(['@A@', '@B@', '@C@', '@D@', '@E@', '@F@', '@G@', '@H@', '@I@'], (n_contr, n_parte, n_comp, n_comp, n_desc, n_cita, n_pares - n_cita, n_conoc, n_cam)):
    cab = cab.replace(tok, str(val))


c1 = ("| **DX-C1** | ✅ **abierta por la sesión principal** (01-10-2026: `python tools/vecinos-brd.py RN-383` y una consulta a `tools/buscar-brd.py`; "
      "lo demás se midió en una copia de `tools/` en el scratchpad, sin tocar el repositorio) | **El vecindario y el buscador no ven los siete estados persistentes `DA-EST-001` a `007` ni las nueve notas de vocabulario `NT-001` a `NT-009`**, "
      "aunque 84 elementos citan al menos un `DA-EST` (94 citas) y 38 citan al menos una nota `NT` (`NT-003`: 18, `NT-008`: 11, `NT-002`: 7). "
      "*Prueba 1:* `RN-383` cita a `DA-EST-002`, y `vecinos-brd.py RN-383` lista 22 elementos en «SALE A» sin él. "
      "*Prueba 2:* `python tools/buscar-brd.py \"estado persistente registro de la atencion cobrada corte registrado\"` devuelve `RN-296`, `CA-266`, `CA-234`, `CA-097` y `RN-279` "
      "y no devuelve `DA-EST-002`, que es la definición del registro que la factura cuenta; el buscador dice buscar «de 1837 filas», las que `vecinos-brd.py` carga. "
      "*Causa:* el prefijo `_PREF` de `tools/vecinos-brd.py` no trae `DA-EST` y las notas `NT-` son citas en bloque, no filas de tabla; `ID_BRD` de `tools/cazador-obsoletos.py` tampoco trae `DA-EST` ni `NT`, "
      "así que su `--relectura` no cuenta como tocados a `DA-EST-004` a `007` ni a `NT-009`. Siete herramientas cargan `vecinos-brd.py` (`auditoria-sesiones`, `brd-guardian`, `buscar-brd`, `elemento`, `historia`, `regla-en-la-respuesta`, `spec-requisitos`). "
      "*Medido en la copia con `DA-EST` agregado a las dos expresiones:* `vecinos-brd` carga 1.837 → 1.844 elementos y 9.930 → 10.199 citas, y el «SALE A» de 81 elementos cambia (`RN-383`: 22 → 23); "
      "`cazador-obsoletos` cuenta 1.839 → 1.846 elementos y sus cinco hallazgos (2 nuevos y 3 ya enrutados) son los mismos antes y después. "
      "*No se midió:* `regresion-controles.py`, `sincronia-skill.py` ni las cifras que otros controles imprimen con esas herramientas | "
      "`tools/vecinos-brd.py`, `tools/cazador-obsoletos.py`, `tools/buscar-brd.py`, `DA-EST-002`, `RN-383` | "
      "Agregar `DA-EST` a las dos expresiones (una palabra en cada una); las notas `NT-` piden un cargador aparte porque no son filas de tabla; correr `regresion-controles.py` y `sincronia-skill.py` con el cambio y subir la copia a la skill `crea-suite`. "
      "Antes de proponerlo como cambio faltan la cifra de después de esos dos controles y qué se rompería | "
      "**(a)** Claude, midiendo antes: una propuesta sobre el método llega con la cifra de antes, la de después y qué se rompería, y aquí falta la segunda mitad |")
c2 = ("| **DX-C2** | ✅ **abierta por la sesión principal** (01-10-2026, con el texto de `RN-383` y de `RN-150`, `CA-815` y `RN-338` abierto donde el control señala) | "
      "**Los dos hallazgos nuevos de `cazador-obsoletos.py` en la v5.83 son falsos positivos.** (1) `[O1]` sobre `RN-383` dice que el titular anuncia «CUATRO TIEMPOS» y que la enumeración llega a (5): ese «(5)» está dentro de la marca `[DERIVADO: RN-183, RN-333, RN-407 (5)]` y nombra el ítem 5 de `RN-407`; los tiempos de `RN-383` son cuatro. "
      "(2) `[O3a]` sobre `RN-150` dice que lo citan con números distintos (2 y 4): `CA-815` dice «los cuatro negativos de `RN-150`» y `RN-150` abre con «Los negativos son cuatro», mientras `RN-338` habla de «las dos puertas de `RN-150`/`RN-151`», que es otra cosa | "
      "`RN-383`, `RN-150`, `CA-815`, `RN-338`, `tools/cazador-obsoletos.py` | "
      "Dejar los dos como conocidos con `cazador-obsoletos.py --sellar` (esta fila los enruta). Mejorar el control —que `O1` no cuente un «(n)» que sigue a un ID dentro de una marca, y que `O3a` compare solo números que cuentan el mismo sustantivo— llegaría con su medición (antes: 2 de 2 hallazgos nuevos eran falsos; después: sin medir) | "
      "**(a)** Claude |")

c3 = ("| **DX-C3** | ✅ **abierta por la sesión principal** (01-10-2026: al agregar este bloque, `python tools/citas-verificadas.py` pasó de «19 filas SIN VERIFICAR, 0 citas que no se sostienen» a «111 y 15»; se abrieron las 15 con un recorrido propio de las filas DX) | "
      "**Cada control trae su propia copia de la lista de familias de ID, y tres la tienen incompleta.** En el BRD vivo hay estas familias: `AL`, `AL-F`, `AC`, `AC-ECO`, `AC-REG`, `OB`, `PR`, `PR-ALT`, `PR-EXC`, `RN`, `CB`, `CE`, `PZ`, `RE`, `SA`, `RG`, `PE`, `BN`, `CA`, `DA-IN`, `DA-OUT`, `DA-CON`, `DA-EST` y `NT` (más `INV` en la evidencia). "
      "`tools/vecinos-brd.py` no trae `DA-EST` ni las notas `NT`; `tools/cazador-obsoletos.py` no trae `DA-EST` ni `NT` (`DX-C1`); `tools/citas-verificadas.py` no trae `AC`, `AC-ECO`, `AC-REG`, `DA-CON`, `BN` ni `NT`: **una cita literal que una fila toma de uno de esos elementos no se comprueba y el control la cuenta como «no se sostiene»**. "
      "De las 15 citas que el control no encontró en las filas DX, las que se abrieron son de tres clases: literales de elementos `AC-`, `NT-` o `AC-ECO-` (familias que el control no abre), literales de un elemento que no estaba a menos de 180 caracteres de la cita en la fila, y frases que no eran literales —paráfrasis o puntos suspensivos de un lector que habían quedado entre comillas—. "
      "Para no dejar falsos «no se sostiene» en una cifra que se sigue en cada arranque, las frases de los lectores que no son citas se escribieron sin comillas de cita y las citas literales de familias que el control no abre se escribieron entre ‹ › (que el control ignora); esas las comprobó el script que generó las filas con `comun.contiene`, no el control. "
      "*No se midió:* cuántos otros controles tienen su copia de la lista ni cuáles la tienen incompleta; `docs-check.py`, `docs-fresh.py`, `mapa-brd.py` y `nivel-programable.py` no se miraron | "
      "`tools/vecinos-brd.py`, `tools/cazador-obsoletos.py`, `tools/citas-verificadas.py`, `tools/comun.py` | "
      "Una sola lista de familias en `tools/comun.py` que importen todos los controles, y una prueba que la compare contra las familias que de verdad hay en `docs/BRD.md`. Antes de proponerlo hay que medir qué familias ve hoy cada control (antes), qué ven con la lista única (después) y qué cifras que imprimen los controles cambian (`regresion-controles.py`); su copia viaja a la skill `crea-suite` | "
      "**(a)** Claude, midiendo antes |")
enc = "| # | Origen | Qué pasa | Base | Qué hacer | Quién resuelve |\n|---|---|---|---|---|---|"
cola = ("\n\n### Los %d pares que el segundo lector dio por compatibles (no son filas)\n\n"
        "**Se listan para que la próxima cacería no los reporte otra vez**; cada razón es la del segundo lector, que abrió los dos elementos y a lo más dos vecinos. "
        "Si alguna razón no convence, el par se reabre con `tools/elemento.py` y se escribe como fila nueva.\n\n" % n_desc)
txt = titulo + "\n" + cab + "\n" + enc + "\n" + c1 + "\n" + c2 + "\n" + c3 + "\n" + filas + cola + desc + "\n"
io.open(os.path.join(SP, "dx_bloque.md"), "w", encoding="utf-8").write(txt)
print("bloque escrito:", len(txt), "caracteres;", txt.count("\n| **DX-"), "filas de tabla DX")
